version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:8888"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://service-db:3306/online-shop
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=LeraMam
    #  - spring.datasource.url=jdbc:mysql://service-db:3306/online-shop
    #  - spring.datasource.username=root
    #  - spring.datasource.password=LeraMam

  service-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: online-shop
      MYSQL_ROOT_PASSWORD: LeraMam
    ports:
      - "3307:3306"

    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  db-data:
  pgadmin-data: